### ISSUE TITLE
Edit to Running Luminescent under Maven Wiki

### ISSUE THREAD

**Issue by RJP43** [wendellpiez/Luminescent#1]
@wendellpiez in the wiki [Running Luminescent under Maven](https://github.com/wendellpiez/Luminescent/wiki/Running-Luminescent-under-Maven) you say "A bunch of stuff should happen. If all is well, the system will pause when it has set up a server on port 8888. When this happens, you should see Luminescent visible here: localhost:8888/Luminescent/lmnl "

however, Luminescent is visible here instead:

http://localhost:8888/cocoon/Luminescent/lmnl

Does this sound right? When we tried to check with the localhost address listed in the WIKI we got an error saying "No block for /Luminescent/lmnl" ... when we referred back to the email conversation you said check using the other localhost address, which worked. So be good idea to change the WIKI to correspond with your email directions.

**Comment by RJP43** [comment]
Also, do you get this warning:

![screenshot_1](https://cloud.githubusercontent.com/assets/8645521/13103662/ed03fbc2-d525-11e5-9c99-18c4d6d78354.jpg)

Is this a problem with just with my maven setup, or the Jetty server, or a missing file in cocoon? 

Since it is running I am guessing it doesn't really affect anything, but was curious if you have the same warning message? 

Sounds like an error in initializing a web server based off what we found when searching for this warning, but wasn't sure if the error was coming from our individual setup and configuration or what?

**Comment by wendellpiez** [comment]
Thanks so much for poking at this.

First of all I am super sorry for leaving off the 'cocoon' step in the URL I gave. You were able to see what the correct one is. Thanks for persisting.

Second, with regard to the Java logging error, the problem is in Cocoon somewhere, running under Jetty, so not only you but anyone who invokes it this way will see it. When I have asked Java people about this they have told me it is innocuous. If I knew how to set up the pom.xml or other settings so the noise would not be echoed to stdout, I'd be happy. It is something about the way Jetty is interfaced for error logging, so perhaps a patch to Cocoon is necessary to avoid it properly, although one might also be able to find a workaround via the pom.xml somehow. (Help is always appreciated, I am not a Java web application engineer.) Logging can also presumably also be turned off entirely if you know how to do it.
